### ISSUE TITLE
请问如何安装到chrome

### ISSUE THREAD

**Issue by falltree** [zluo01/115-Exporter#286]
没有看明白chrome安装的介绍，是修改什么文件或chrome设置？
Change

  "background": {
    "scripts": [
      "background/index.js"
    ],
    "type": "module"
  },
to

  "background": {
    "service_worker": "background/index.js",
    "type": "module"
  },

**Comment by zluo01** [comment]
https://github.com/zluo01/115-Exporter/blob/main/src/manifest.ts#L15-L18

**Comment by falltree** [comment]
多谢指明修改位置，但还是没有搞明白，修改了这个文件后，需要如何操作才把插件安装到chrome？
这些文件不是crx，也和crx解压后的文件结构不一样，非码农不知该怎么处理。

**Comment by zluo01** [comment]
https://developer.chrome.com/docs/extensions/get-started/tutorial/hello-world#load-unpacked

**Comment by falltree** [comment]
> https://developer.chrome.com/docs/extensions/get-started/tutorial/hello-world#load-unpacked

发帖之前已经这样试过，并不成功，chrome无法找到任何可安装的插件。
其他别的crx，是可以解压，放到一个目录里，然后用chrome安装解压的包，可以正常安装。
这些可安装的crx解压后，都有一个manifest.json文件，而这里的115插件并没有。
希望能得更进一步的说明，谢谢。
